import AccountTreeOutlinedIcon from '@mui/icons-material/AccountTreeOutlined'
import BiotechOutlinedIcon from '@mui/icons-material/BiotechOutlined'
import CalculateOutlinedIcon from '@mui/icons-material/CalculateOutlined'
import CategoryOutlinedIcon from '@mui/icons-material/CategoryOutlined'
import FunctionsOutlinedIcon from '@mui/icons-material/FunctionsOutlined'
import HubOutlinedIcon from '@mui/icons-material/HubOutlined'
import ScienceOutlinedIcon from '@mui/icons-material/ScienceOutlined'
import ShowChartOutlinedIcon from '@mui/icons-material/ShowChartOutlined'
import TableChartOutlinedIcon from '@mui/icons-material/TableChartOutlined'
import ViewInArOutlinedIcon from '@mui/icons-material/ViewInArOutlined'
import type { ReactNode } from 'react'
import { BiologySimulationBuilder, BiologySimulationPlayer, CalculatorBuilder, CalculatorPlayer, ChemicalEquationBuilder, ChemicalEquationPlayer, ChemistrySimulationBuilder, ChemistrySimulationPlayer, ClassificationBuilder, ClassificationPlayer, CircuitBuilder, CircuitPlayer, DiagramBuilder, DiagramPlayer, FormulaBuilder, FormulaPlayer, GeometryBuilder, GeometryPlayer, GraphBuilder, GraphPlayer, LabEnvironmentBuilder, LabEnvironmentPlayer, LinearEquationBuilder, LinearEquationPlayer, MoleculeBuilder, MoleculePlayer, PeriodicTableBuilder, PeriodicTablePlayer, PhysicsSimulationBuilder, PhysicsSimulationPlayer, PunnettBuilder, PunnettPlayer, ThreeDExplorerBuilder, ThreeDExplorerPlayer, balanceChemicalEquation, solveLinearEquation } from './stem-tool-components'
import { evaluateExpression, graphPoints, type LabScenario } from './stem-engines'
import type { StemBiologySimulationConfig, StemCalculatorConfig, StemChemicalEquationConfig, StemChemistrySimulationConfig, StemCircuitConfig, StemClassificationConfig, StemDiagramConfig, StemFormulaConfig, StemGeometryConfig, StemGraphConfig, StemLabConfig, StemLabEnvironmentConfig, StemLinearEquationConfig, StemMoleculeConfig, StemPeriodicTableConfig, StemPhysicsSimulationConfig, StemPunnettConfig, StemSubject, StemSubtype, StemThreeDConfig, StemTool, StemToolDefinition } from './stem-types'

const formula = (topic: string, expression: string): StemFormulaConfig => ({ version: 1, topic, instructions: 'Enter the known values, calculate the result, then record your completed calculation.', formula: expression, solveFor: 'Result' })
const lab = (activity: StemLabEnvironmentConfig['activity'], scenario: LabScenario, instructions: string): StemLabEnvironmentConfig => ({ version: 1, topic: `${activity === 'experiment' ? 'Experiment' : 'Virtual lab'} · ${scenario}`, instructions, scenario, activity, steps: ['Set up the required equipment.', 'Run the procedure with the provided inputs.', 'Record one observation.'] })
const validGraph = (config: StemLabConfig) => { const item = config as StemGraphConfig; return Boolean(item.instructions.trim() && item.expression.includes('x') && graphPoints(item.expression, -2, 2, 20).length > 1) }
const validCalculator = (config: StemLabConfig) => { const item = config as StemCalculatorConfig; return Boolean(item.instructions.trim() && Number.isFinite(evaluateExpression(item.initialExpression))) }
const validFormula = (config: StemLabConfig) => { const item = config as StemFormulaConfig; return Boolean(item.instructions.trim() && item.formula.includes('=') && item.solveFor.trim()) }
const validLinearEquation = (config: StemLabConfig) => { const item = config as StemLinearEquationConfig; return Boolean(item.instructions.trim() && Number.isFinite(solveLinearEquation(item.equation))) }
const validGeometry = (config: StemLabConfig) => Boolean((config as StemGeometryConfig).instructions.trim())
const validPhysicsSimulation = (config: StemLabConfig) => Boolean((config as StemPhysicsSimulationConfig).instructions.trim())
const validChemistrySimulation = (config: StemLabConfig) => Boolean((config as StemChemistrySimulationConfig).instructions.trim())
const validBiologySimulation = (config: StemLabConfig) => Boolean((config as StemBiologySimulationConfig).instructions.trim())
const validLab = (config: StemLabConfig) => { const item = config as StemLabEnvironmentConfig; return Boolean(item.instructions.trim() && item.steps.length && item.steps.every((step) => step.trim())) }
const validCircuit = (config: StemLabConfig) => { const item = config as StemCircuitConfig; return Boolean(item.instructions.trim() && Number.isFinite(item.voltage) && item.resistors.length && item.resistors.every((resistance) => Number.isFinite(resistance) && resistance > 0)) }
const validMolecule = (config: StemLabConfig) => { const item = config as StemMoleculeConfig; return Boolean(item.instructions.trim() && /^(?:[A-Z][a-z]?\d*)+$/.test(item.targetFormula.replace(/\s+/g, ''))) }
const validPeriodicTable = (config: StemLabConfig) => { const item = config as StemPeriodicTableConfig; return Boolean(item.instructions.trim() && item.targetAtomicNumbers.length && item.targetAtomicNumbers.every((number) => Number.isInteger(number) && number >= 1 && number <= 118)) }
const validChemicalEquation = (config: StemLabConfig) => { const item = config as StemChemicalEquationConfig; return Boolean(item.instructions.trim() && balanceChemicalEquation(item.equation)) }
const validDiagram = (config: StemLabConfig) => { const item = config as StemDiagramConfig; return Boolean(item.instructions.trim() && item.imageUrl && item.hotspots.length) }
const validThreeD = (config: StemLabConfig) => { const item = config as StemThreeDConfig; return Boolean(item.instructions.trim() && item.requiredLabels.length) }
const validPunnett = (config: StemLabConfig) => { const item = config as StemPunnettConfig; return Boolean(item.instructions.trim() && /^[A-Za-z]{2}$/.test(item.parentOne) && /^[A-Za-z]{2}$/.test(item.parentTwo) && item.dominantTrait.trim() && item.recessiveTrait.trim()) }
const validClassification = (config: StemLabConfig) => { const item = config as StemClassificationConfig; return Boolean(item.instructions.trim() && item.categories.length >= 2 && item.items.length && item.items.every((entry) => entry.label.trim() && item.categories.includes(entry.category))) }

const definition = (subject: StemSubject, tool: StemTool, label: string, icon: ReactNode, Builder: StemToolDefinition['Builder'], Player: StemToolDefinition['Player'], mode: StemToolDefinition['mode'], defaultConfig: StemLabConfig, isConfigured: StemToolDefinition['isConfigured']): StemToolDefinition => ({ subject, tool, subtype: `${subject}.${tool}` as StemSubtype, label, icon, Builder, Player, mode, defaultConfig, isConfigured })

export const STEM_LAB_REGISTRY: StemToolDefinition[] = [
  definition('math', 'graph', 'Graph', <ShowChartOutlinedIcon />, GraphBuilder, GraphPlayer, 'build', { version: 1, topic: 'Functions', instructions: 'Plot the function, inspect its behavior, and record the requested value.', expression: 'x^2', targetX: 2 }, validGraph),
  definition('math', 'equation_solver', 'Equation Solver', <FunctionsOutlinedIcon />, LinearEquationBuilder, LinearEquationPlayer, 'build', { version: 1, topic: 'Linear equations', instructions: 'Solve the linear equation for x.', equation: '2x + 3 = 11' }, validLinearEquation),
  definition('math', 'calculator', 'Calculator', <CalculateOutlinedIcon />, CalculatorBuilder, CalculatorPlayer, 'build', { version: 1, topic: 'Arithmetic', instructions: 'Evaluate the expression and record the result.', initialExpression: '2 + 3 * 4' }, validCalculator),
  definition('math', 'geometry_builder', 'Geometry Builder', <AccountTreeOutlinedIcon />, GeometryBuilder, GeometryPlayer, 'build', { version: 1, topic: 'Geometry construction', instructions: 'Plot the requested snapped vertices, inspect the measurements, then record the construction.', requiredVertices: 3 }, validGeometry),

  definition('physics', 'graph', 'Graph', <ShowChartOutlinedIcon />, GraphBuilder, GraphPlayer, 'build', { version: 1, topic: 'Physics graph', instructions: 'Plot the function, inspect its behavior, and record the requested value.', expression: '2*x + 1', targetX: 2 }, validGraph),
  definition('physics', 'simulation', 'Simulation', <ScienceOutlinedIcon />, PhysicsSimulationBuilder, PhysicsSimulationPlayer, 'build', { version: 1, topic: 'Kinematics', instructions: 'Run the named physics model with the supplied inputs, then record the calculated state.', scenario: 'projectile_motion' }, validPhysicsSimulation),
  definition('physics', 'formula_solver', 'Calculator / Formula Solver', <CalculateOutlinedIcon />, FormulaBuilder, FormulaPlayer, 'build', formula('Physics calculation', 'F = m * a'), validFormula),
  definition('physics', 'experiment', 'Experiment', <BiotechOutlinedIcon />, LabEnvironmentBuilder, LabEnvironmentPlayer, 'build', lab('experiment', 'pendulum', 'Follow each procedure step, enter the measurements, then record an observation.'), validLab),
  definition('physics', 'virtual_lab', 'Virtual Lab', <BiotechOutlinedIcon />, LabEnvironmentBuilder, LabEnvironmentPlayer, 'build', lab('virtual_lab', 'pendulum', 'Set up the apparatus, run the virtual lab, then record an observation.'), validLab),
  definition('physics', 'circuit_builder', 'Circuit Builder', <HubOutlinedIcon />, CircuitBuilder, CircuitPlayer, 'build', { version: 1, topic: 'Simple circuits', instructions: 'Build the configured circuit, calculate the total current, then record the result.', topology: 'series', voltage: 12, resistors: [10, 20] }, validCircuit),

  definition('chemistry', 'formula_solver', 'Calculator / Formula Solver', <CalculateOutlinedIcon />, FormulaBuilder, FormulaPlayer, 'build', formula('Chemistry calculation', 'Result = m / V'), validFormula),
  definition('chemistry', 'periodic_table', 'Periodic Table', <TableChartOutlinedIcon />, PeriodicTableBuilder, PeriodicTablePlayer, 'build', { version: 1, topic: 'Element identification', instructions: 'Select every target element from the periodic table.', targetAtomicNumbers: [1, 6, 8] }, validPeriodicTable),
  definition('chemistry', 'molecule_builder', 'Molecule Builder', <ViewInArOutlinedIcon />, MoleculeBuilder, MoleculePlayer, 'build', { version: 1, topic: 'Molecular structures', instructions: 'Build the requested molecule with the correct atoms and bonds.', targetFormula: 'H2O' }, validMolecule),
  definition('chemistry', 'chemical_equation', 'Chemical Equation', <FunctionsOutlinedIcon />, ChemicalEquationBuilder, ChemicalEquationPlayer, 'build', { version: 1, topic: 'Balancing equations', instructions: 'Balance the equation with the smallest whole-number coefficients.', equation: 'Fe + O2 -> Fe2O3' }, validChemicalEquation),
  definition('chemistry', 'simulation', 'Simulation', <ScienceOutlinedIcon />, ChemistrySimulationBuilder, ChemistrySimulationPlayer, 'build', { version: 1, topic: 'Reaction models', instructions: 'Run the named chemistry model with the supplied inputs, then record the calculated state.', scenario: 'reaction_rate' }, validChemistrySimulation),
  definition('chemistry', 'virtual_lab', 'Virtual Lab', <BiotechOutlinedIcon />, LabEnvironmentBuilder, LabEnvironmentPlayer, 'build', lab('virtual_lab', 'neutralization', 'Set up the chemistry equipment, run the neutralization procedure, then record an observation.'), validLab),
  definition('chemistry', 'experiment', 'Experiment', <BiotechOutlinedIcon />, LabEnvironmentBuilder, LabEnvironmentPlayer, 'build', lab('experiment', 'neutralization', 'Follow each chemistry procedure step, enter the measurements, then record an observation.'), validLab),

  definition('biology', 'interactive_diagram', 'Interactive Diagram', <AccountTreeOutlinedIcon />, DiagramBuilder, DiagramPlayer, 'build', { version: 1, topic: 'Biology diagram', instructions: 'Open every labeled hotspot to explore the diagram.', imageUrl: '', hotspots: [] }, validDiagram),
  definition('biology', 'three_d_explorer', '3D Explorer', <ViewInArOutlinedIcon />, ThreeDExplorerBuilder, ThreeDExplorerPlayer, 'build', { version: 1, topic: 'Biology models', instructions: 'Inspect the model and open every required label.', model: 'cell', requiredLabels: ['Nucleus', 'Mitochondrion', 'Vacuole', 'Cell membrane', 'Cytoplasm'] }, validThreeD),
  definition('biology', 'virtual_lab', 'Virtual Lab', <BiotechOutlinedIcon />, LabEnvironmentBuilder, LabEnvironmentPlayer, 'build', lab('virtual_lab', 'osmosis', 'Set up the biology equipment, run the osmosis procedure, then record an observation.'), validLab),
  definition('biology', 'simulation', 'Simulation', <ScienceOutlinedIcon />, BiologySimulationBuilder, BiologySimulationPlayer, 'build', { version: 1, topic: 'Biology models', instructions: 'Run the named biology model with the supplied inputs, then record the calculated state.', scenario: 'population_growth' }, validBiologySimulation),
  definition('biology', 'genetics_punnett_square', 'Genetics / Punnett Square', <CategoryOutlinedIcon />, PunnettBuilder, PunnettPlayer, 'build', { version: 1, topic: 'Mendelian genetics', instructions: 'Use the Punnett square, then calculate the dominant phenotype percentage.', parentOne: 'Aa', parentTwo: 'Aa', dominantTrait: 'Dominant trait', recessiveTrait: 'Recessive trait' }, validPunnett),
  definition('biology', 'classification_builder', 'Classification Builder', <CategoryOutlinedIcon />, ClassificationBuilder, ClassificationPlayer, 'build', { version: 1, topic: 'Classification', instructions: 'Drag every item into its correct category.', categories: ['Category A', 'Category B'], items: [{ id: 1, label: 'Item 1', category: 'Category A' }, { id: 2, label: 'Item 2', category: 'Category B' }] }, validClassification),
  definition('biology', 'experiment', 'Experiment', <BiotechOutlinedIcon />, LabEnvironmentBuilder, LabEnvironmentPlayer, 'build', lab('experiment', 'osmosis', 'Follow each biology procedure step, enter the measurements, then record an observation.'), validLab),
]

export const getStemToolsForSubject = (subject: StemSubject) => STEM_LAB_REGISTRY.filter((definition) => definition.subject === subject)
export const getStemTool = (subject?: StemSubject, tool?: StemTool) => STEM_LAB_REGISTRY.find((definition) => definition.subject === subject && definition.tool === tool)
export const getStemToolBySubtype = (subtype?: string) => STEM_LAB_REGISTRY.find((definition) => definition.subtype === subtype)
export const defaultStemLabConfig = (subject: StemSubject, tool: StemTool) => structuredClone(getStemTool(subject, tool)?.defaultConfig ?? STEM_LAB_REGISTRY[0].defaultConfig)
