CREATE TABLE IF NOT EXISTS "grade_levels" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "classes" INTEGER NOT NULL DEFAULT 0,
  "students" INTEGER NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'Draft',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "grade_levels_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "class_sections" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "grade" TEXT NOT NULL,
  "students" INTEGER NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'Draft',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "class_sections_pkey" PRIMARY KEY ("id")
);
